name: Web Front-end Tests

on:
  push: []
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  web_front-end_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing on Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install general dependencies
      run: npm install
    - name: Install dependencies to do E2E tests
      run: npx playwright install --with-deps
    - name: Install server to check grammar
      run: npx gramma server install
    - name: Identify the server before explicitly enabling it to check grammar
      run: npx gramma server info
    - name: Initiate server to check grammar
      run: npx gramma server start
    - name: Identify the server after explicitly enabling it to check grammar
      run: npx gramma server info
    - run: npm run test:e2e
